package tiermailgen.tiermailgen.model;
// Generated Mar 22, 2019 3:31:31 PM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * ApptransRegRel generated by hbm2java
 */
@Entity
@Table(name = "apptrans_reg_rel")
public class ApptransRegRel implements java.io.Serializable {

	private Integer appTransRegRelUid;
	private AppTransactions appTransactions;
	//private RegistrationItems registrationItems;
	
	private int regItemUid;
	private int appRegItemStatusUid;
	private int requestActionsUid;
	private Integer decisionActionUid;
	private Date decisionDate;
	private Character fulFilledFlag;
	private BigDecimal regItemAmount;
	private BigDecimal feeAdjustAmount;
	private Date calulatedExpiration;
	private Integer tokenAllowCount;
	private Integer tokenCount;
	private Date tokenExpDate;
	private Date issuanceDate;
	private Character withdrawRequestFlag;
	private Date withdrawRequestDate;
	private Character placardRequestFlag;
	private Character stickerRequestFlag;
	private Date actionRequestedDate;
	private String actionRequestedBy;
	private String createModifiedBy;
	private Date createModifiedDate;

	public ApptransRegRel() {
	}

	public ApptransRegRel(AppTransactions appTransactions, RegistrationItems registrationItems, int appRegItemStatusUid,
			int requestActionsUid, BigDecimal regItemAmount, String createModifiedBy, Date createModifiedDate) {
		this.appTransactions = appTransactions;
	//	this.registrationItems = registrationItems;
		this.appRegItemStatusUid = appRegItemStatusUid;
		this.requestActionsUid = requestActionsUid;
		this.regItemAmount = regItemAmount;
		this.createModifiedBy = createModifiedBy;
		this.createModifiedDate = createModifiedDate;
	}

	public ApptransRegRel(AppTransactions appTransactions, RegistrationItems registrationItems, int appRegItemStatusUid,
			int requestActionsUid, Integer decisionActionUid, Date decisionDate, Character fulFilledFlag,
			BigDecimal regItemAmount, BigDecimal feeAdjustAmount, Date calulatedExpiration, Integer tokenAllowCount,
			Integer tokenCount, Date tokenExpDate, Date issuanceDate, Character withdrawRequestFlag,
			Date withdrawRequestDate, Character placardRequestFlag, Character stickerRequestFlag,
			Date actionRequestedDate, String actionRequestedBy, String createModifiedBy, Date createModifiedDate) {
		this.appTransactions = appTransactions;
		//this.registrationItems = registrationItems;
		this.appRegItemStatusUid = appRegItemStatusUid;
		this.requestActionsUid = requestActionsUid;
		this.decisionActionUid = decisionActionUid;
		this.decisionDate = decisionDate;
		this.fulFilledFlag = fulFilledFlag;
		this.regItemAmount = regItemAmount;
		this.feeAdjustAmount = feeAdjustAmount;
		this.calulatedExpiration = calulatedExpiration;
		this.tokenAllowCount = tokenAllowCount;
		this.tokenCount = tokenCount;
		this.tokenExpDate = tokenExpDate;
		this.issuanceDate = issuanceDate;
		this.withdrawRequestFlag = withdrawRequestFlag;
		this.withdrawRequestDate = withdrawRequestDate;
		this.placardRequestFlag = placardRequestFlag;
		this.stickerRequestFlag = stickerRequestFlag;
		this.actionRequestedDate = actionRequestedDate;
		this.actionRequestedBy = actionRequestedBy;
		this.createModifiedBy = createModifiedBy;
		this.createModifiedDate = createModifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AppTransRegRel_UID", unique = true, nullable = false)
	public Integer getAppTransRegRelUid() {
		return this.appTransRegRelUid;
	}

	public void setAppTransRegRelUid(Integer appTransRegRelUid) {
		this.appTransRegRelUid = appTransRegRelUid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AppTrans_UID", nullable = false)
	public AppTransactions getAppTransactions() {
		return this.appTransactions;
	}

	public void setAppTransactions(AppTransactions appTransactions) {
		this.appTransactions = appTransactions;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "RegItem_UID", insertable = false, updatable = false, nullable = false)
	/*public RegistrationItems getRegistrationItems() {
		return this.registrationItems;
	}

	public void setRegistrationItems(RegistrationItems registrationItems) {
		this.registrationItems = registrationItems;
	}*/
	//@Transient
	@Column(name = "RegItem_UID", nullable = false)
	public int getRegItemUid() {
		return regItemUid;
	}

	public void setRegItemUid(int regItemUid) {
		this.regItemUid = regItemUid;
	}

	@Column(name = "AppRegItemStatus_UID", nullable = false)
	public int getAppRegItemStatusUid() {
		return this.appRegItemStatusUid;
	}
	
	public void setAppRegItemStatusUid(int appRegItemStatusUid) {
		this.appRegItemStatusUid = appRegItemStatusUid;
	}

	@Column(name = "RequestActions_UID", nullable = false)
	public int getRequestActionsUid() {
		return this.requestActionsUid;
	}

	public void setRequestActionsUid(int requestActionsUid) {
		this.requestActionsUid = requestActionsUid;
	}

	@Column(name = "DecisionAction_UID")
	public Integer getDecisionActionUid() {
		return this.decisionActionUid;
	}

	public void setDecisionActionUid(Integer decisionActionUid) {
		this.decisionActionUid = decisionActionUid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Decision_Date", length = 10)
	public Date getDecisionDate() {
		return this.decisionDate;
	}

	public void setDecisionDate(Date decisionDate) {
		this.decisionDate = decisionDate;
	}

	@Column(name = "FulFilled_Flag", length = 1)
	public Character getFulFilledFlag() {
		return this.fulFilledFlag;
	}

	public void setFulFilledFlag(Character fulFilledFlag) {
		this.fulFilledFlag = fulFilledFlag;
	}

	@Column(name = "RegItem_Amount", nullable = false, precision = 10)
	public BigDecimal getRegItemAmount() {
		return this.regItemAmount;
	}

	public void setRegItemAmount(BigDecimal regItemAmount) {
		this.regItemAmount = regItemAmount;
	}

	@Column(name = "Fee_Adjust_Amount", precision = 10)
	public BigDecimal getFeeAdjustAmount() {
		return this.feeAdjustAmount;
	}

	public void setFeeAdjustAmount(BigDecimal feeAdjustAmount) {
		this.feeAdjustAmount = feeAdjustAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Calulated_Expiration", length = 10)
	public Date getCalulatedExpiration() {
		return this.calulatedExpiration;
	}

	public void setCalulatedExpiration(Date calulatedExpiration) {
		this.calulatedExpiration = calulatedExpiration;
	}

	@Column(name = "Token_Allow_Count")
	public Integer getTokenAllowCount() {
		return this.tokenAllowCount;
	}

	public void setTokenAllowCount(Integer tokenAllowCount) {
		this.tokenAllowCount = tokenAllowCount;
	}

	@Column(name = "Token_Count")
	public Integer getTokenCount() {
		return this.tokenCount;
	}

	public void setTokenCount(Integer tokenCount) {
		this.tokenCount = tokenCount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Token_Exp_Date", length = 10)
	public Date getTokenExpDate() {
		return this.tokenExpDate;
	}

	public void setTokenExpDate(Date tokenExpDate) {
		this.tokenExpDate = tokenExpDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Issuance_Date", length = 19)
	public Date getIssuanceDate() {
		return this.issuanceDate;
	}

	public void setIssuanceDate(Date issuanceDate) {
		this.issuanceDate = issuanceDate;
	}

	@Column(name = "Withdraw_Request_Flag", length = 1)
	public Character getWithdrawRequestFlag() {
		return this.withdrawRequestFlag;
	}

	public void setWithdrawRequestFlag(Character withdrawRequestFlag) {
		this.withdrawRequestFlag = withdrawRequestFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Withdraw_Request_Date", length = 19)
	public Date getWithdrawRequestDate() {
		return this.withdrawRequestDate;
	}

	public void setWithdrawRequestDate(Date withdrawRequestDate) {
		this.withdrawRequestDate = withdrawRequestDate;
	}

	@Column(name = "Placard_Request_Flag", length = 1)
	public Character getPlacardRequestFlag() {
		return this.placardRequestFlag;
	}

	public void setPlacardRequestFlag(Character placardRequestFlag) {
		this.placardRequestFlag = placardRequestFlag;
	}

	@Column(name = "Sticker_Request_Flag", length = 1)
	public Character getStickerRequestFlag() {
		return this.stickerRequestFlag;
	}

	public void setStickerRequestFlag(Character stickerRequestFlag) {
		this.stickerRequestFlag = stickerRequestFlag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Action_Requested_Date", length = 10)
	public Date getActionRequestedDate() {
		return this.actionRequestedDate;
	}

	public void setActionRequestedDate(Date actionRequestedDate) {
		this.actionRequestedDate = actionRequestedDate;
	}

	@Column(name = "Action_Requested_By", length = 45)
	public String getActionRequestedBy() {
		return this.actionRequestedBy;
	}

	public void setActionRequestedBy(String actionRequestedBy) {
		this.actionRequestedBy = actionRequestedBy;
	}

	@Column(name = "Create_Modified_By", nullable = false, length = 45)
	public String getCreateModifiedBy() {
		return this.createModifiedBy;
	}

	public void setCreateModifiedBy(String createModifiedBy) {
		this.createModifiedBy = createModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Modified_Date", nullable = false, length = 19)
	public Date getCreateModifiedDate() {
		return this.createModifiedDate;
	}

	public void setCreateModifiedDate(Date createModifiedDate) {
		this.createModifiedDate = createModifiedDate;
	}

}
