package tiermailgen.tiermailgen.model;
// Generated Mar 22, 2019 3:31:31 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppTransAssociation generated by hbm2java
 */
@Entity
@Table(name = "app_trans_association")
public class AppTransAssociation implements java.io.Serializable {

	private Integer appTransAssocUid;
	private AppTransactions appTransactions;
	private int applicationUid;
	private String createModifiedBy;
	private Date createModifiedDate;

	public AppTransAssociation() {
	}

	public AppTransAssociation(AppTransactions appTransactions, int applicationUid, String createModifiedBy,
			Date createModifiedDate) {
		this.appTransactions = appTransactions;
		this.applicationUid = applicationUid;
		this.createModifiedBy = createModifiedBy;
		this.createModifiedDate = createModifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AppTransAssoc_UID", unique = true, nullable = false)
	public Integer getAppTransAssocUid() {
		return this.appTransAssocUid;
	}

	public void setAppTransAssocUid(Integer appTransAssocUid) {
		this.appTransAssocUid = appTransAssocUid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AppTrans_UID", nullable = false)
	public AppTransactions getAppTransactions() {
		return this.appTransactions;
	}

	public void setAppTransactions(AppTransactions appTransactions) {
		this.appTransactions = appTransactions;
	}

	@Column(name = "Application_UID", nullable = false)
	public int getApplicationUid() {
		return this.applicationUid;
	}

	public void setApplicationUid(int applicationUid) {
		this.applicationUid = applicationUid;
	}

	@Column(name = "Create_Modified_By", nullable = false, length = 45)
	public String getCreateModifiedBy() {
		return this.createModifiedBy;
	}

	public void setCreateModifiedBy(String createModifiedBy) {
		this.createModifiedBy = createModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Modified_Date", nullable = false, length = 19)
	public Date getCreateModifiedDate() {
		return this.createModifiedDate;
	}

	public void setCreateModifiedDate(Date createModifiedDate) {
		this.createModifiedDate = createModifiedDate;
	}

}
