package tiermailgen.tiermailgen.model;
// Generated Mar 22, 2019 3:31:31 PM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppTransactions generated by hbm2java
 */
@Entity
@Table(name = "app_transactions")
public class AppTransactions implements java.io.Serializable {

	private Integer appTransUid;
	private int appTransStatusUid;
	private int appTransTypeUid;
	private Integer consultantContactUid;
	private Integer companyUid;
	private Short appBoxNumber;
	private Date clockStartsDate;
	private char externalFlag;
	private char onBatchFlag;
	private char prelimReviewedFlag;
	private BigDecimal transactionAmount;
	private Date closeOutDate;
	private Date requestDate;
	private Date postMarkDate;
	private Date transactionIssuanceDate;
	private char autoGenerateDocsFlag;
	private String createModifiedBy;
	private Date createModifiedDate;
	private Set<Ledger> ledgers = new HashSet<Ledger>(0);
	private Set<ApptransRegRel> apptransRegRels = new HashSet<ApptransRegRel>(0);
	private Set<AppTransAssociation> appTransAssociations = new HashSet<AppTransAssociation>(0);

	public AppTransactions() {
	}

	public AppTransactions(int appTransStatusUid, int appTransTypeUid, char externalFlag, char onBatchFlag,
			char prelimReviewedFlag, char autoGenerateDocsFlag, String createModifiedBy, Date createModifiedDate) {
		this.appTransStatusUid = appTransStatusUid;
		this.appTransTypeUid = appTransTypeUid;
		this.externalFlag = externalFlag;
		this.onBatchFlag = onBatchFlag;
		this.prelimReviewedFlag = prelimReviewedFlag;
		this.autoGenerateDocsFlag = autoGenerateDocsFlag;
		this.createModifiedBy = createModifiedBy;
		this.createModifiedDate = createModifiedDate;
	}

	public AppTransactions(int appTransStatusUid, int appTransTypeUid, Integer consultantContactUid, Integer companyUid,
			Short appBoxNumber, Date clockStartsDate, char externalFlag, char onBatchFlag, char prelimReviewedFlag,
			BigDecimal transactionAmount, Date closeOutDate, Date requestDate, Date postMarkDate,
			Date transactionIssuanceDate, char autoGenerateDocsFlag, String createModifiedBy, Date createModifiedDate,
			Set<Ledger> ledgers, Set<ApptransRegRel> apptransRegRels, Set<AppTransAssociation> appTransAssociations) {
		this.appTransStatusUid = appTransStatusUid;
		this.appTransTypeUid = appTransTypeUid;
		this.consultantContactUid = consultantContactUid;
		this.companyUid = companyUid;
		this.appBoxNumber = appBoxNumber;
		this.clockStartsDate = clockStartsDate;
		this.externalFlag = externalFlag;
		this.onBatchFlag = onBatchFlag;
		this.prelimReviewedFlag = prelimReviewedFlag;
		this.transactionAmount = transactionAmount;
		this.closeOutDate = closeOutDate;
		this.requestDate = requestDate;
		this.postMarkDate = postMarkDate;
		this.transactionIssuanceDate = transactionIssuanceDate;
		this.autoGenerateDocsFlag = autoGenerateDocsFlag;
		this.createModifiedBy = createModifiedBy;
		this.createModifiedDate = createModifiedDate;
		this.ledgers = ledgers;
		this.apptransRegRels = apptransRegRels;
		this.appTransAssociations = appTransAssociations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AppTrans_UID", unique = true, nullable = false)
	public Integer getAppTransUid() {
		return this.appTransUid;
	}

	public void setAppTransUid(Integer appTransUid) {
		this.appTransUid = appTransUid;
	}

	@Column(name = "AppTransStatus_UID", nullable = false)
	public int getAppTransStatusUid() {
		return this.appTransStatusUid;
	}

	public void setAppTransStatusUid(int appTransStatusUid) {
		this.appTransStatusUid = appTransStatusUid;
	}

	@Column(name = "AppTransType_UID", nullable = false)
	public int getAppTransTypeUid() {
		return this.appTransTypeUid;
	}

	public void setAppTransTypeUid(int appTransTypeUid) {
		this.appTransTypeUid = appTransTypeUid;
	}

	@Column(name = "Consultant_Contact_UID")
	public Integer getConsultantContactUid() {
		return this.consultantContactUid;
	}

	public void setConsultantContactUid(Integer consultantContactUid) {
		this.consultantContactUid = consultantContactUid;
	}

	@Column(name = "Company_UID")
	public Integer getCompanyUid() {
		return this.companyUid;
	}

	public void setCompanyUid(Integer companyUid) {
		this.companyUid = companyUid;
	}

	@Column(name = "App_Box_Number")
	public Short getAppBoxNumber() {
		return this.appBoxNumber;
	}

	public void setAppBoxNumber(Short appBoxNumber) {
		this.appBoxNumber = appBoxNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Clock_Starts_Date", length = 19)
	public Date getClockStartsDate() {
		return this.clockStartsDate;
	}

	public void setClockStartsDate(Date clockStartsDate) {
		this.clockStartsDate = clockStartsDate;
	}

	@Column(name = "External_Flag", nullable = false, length = 1)
	public char getExternalFlag() {
		return this.externalFlag;
	}

	public void setExternalFlag(char externalFlag) {
		this.externalFlag = externalFlag;
	}

	@Column(name = "OnBatch_Flag", nullable = false, length = 1)
	public char getOnBatchFlag() {
		return this.onBatchFlag;
	}

	public void setOnBatchFlag(char onBatchFlag) {
		this.onBatchFlag = onBatchFlag;
	}

	@Column(name = "PrelimReviewed_Flag", nullable = false, length = 1)
	public char getPrelimReviewedFlag() {
		return this.prelimReviewedFlag;
	}

	public void setPrelimReviewedFlag(char prelimReviewedFlag) {
		this.prelimReviewedFlag = prelimReviewedFlag;
	}

	@Column(name = "Transaction_Amount", precision = 10)
	public BigDecimal getTransactionAmount() {
		return this.transactionAmount;
	}

	public void setTransactionAmount(BigDecimal transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Close_Out_Date", length = 19)
	public Date getCloseOutDate() {
		return this.closeOutDate;
	}

	public void setCloseOutDate(Date closeOutDate) {
		this.closeOutDate = closeOutDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Request_Date", length = 19)
	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Post_Mark_Date", length = 19)
	public Date getPostMarkDate() {
		return this.postMarkDate;
	}

	public void setPostMarkDate(Date postMarkDate) {
		this.postMarkDate = postMarkDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Transaction_Issuance_Date", length = 10)
	public Date getTransactionIssuanceDate() {
		return this.transactionIssuanceDate;
	}

	public void setTransactionIssuanceDate(Date transactionIssuanceDate) {
		this.transactionIssuanceDate = transactionIssuanceDate;
	}

	@Column(name = "Auto_Generate_Docs_Flag", nullable = false, length = 1)
	public char getAutoGenerateDocsFlag() {
		return this.autoGenerateDocsFlag;
	}

	public void setAutoGenerateDocsFlag(char autoGenerateDocsFlag) {
		this.autoGenerateDocsFlag = autoGenerateDocsFlag;
	}

	@Column(name = "Create_Modified_By", nullable = false, length = 45)
	public String getCreateModifiedBy() {
		return this.createModifiedBy;
	}

	public void setCreateModifiedBy(String createModifiedBy) {
		this.createModifiedBy = createModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Modified_Date", nullable = false, length = 19)
	public Date getCreateModifiedDate() {
		return this.createModifiedDate;
	}

	public void setCreateModifiedDate(Date createModifiedDate) {
		this.createModifiedDate = createModifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appTransactions")
	public Set<Ledger> getLedgers() {
		return this.ledgers;
	}

	public void setLedgers(Set<Ledger> ledgers) {
		this.ledgers = ledgers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appTransactions")
	public Set<ApptransRegRel> getApptransRegRels() {
		return this.apptransRegRels;
	}

	public void setApptransRegRels(Set<ApptransRegRel> apptransRegRels) {
		this.apptransRegRels = apptransRegRels;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "appTransactions")
	@OneToMany(cascade=CascadeType.ALL, mappedBy = "appTransactions")
	public Set<AppTransAssociation> getAppTransAssociations() {
		return this.appTransAssociations;
	}

	public void setAppTransAssociations(Set<AppTransAssociation> appTransAssociations) {
		this.appTransAssociations = appTransAssociations;
	}

}
