package tiermailgen.tiermailgen.model;
// Generated Mar 22, 2019 3:31:31 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TierMailouts generated by hbm2java
 */
@Entity
@Table(name = "tier_mailouts")
public class TierMailouts implements java.io.Serializable {

	private Integer uid;
	private String appno;
	private String regno;
	private String trackingno;
	private char status;
	private Date createModifiedDate;
	private Integer appCount;
	private Integer companyuid;
	private Date expirationDate;
	private Integer regitemuid;

	public Integer getAppCount() {
		return appCount;
	}

	public void setAppCount(Integer appCount) {
		this.appCount = appCount;
	}

	public TierMailouts() {
	}

	public TierMailouts(String appno, String trackingno, char status, Date createModifiedDate) {
		this.appno = appno;
		this.trackingno = trackingno;
		this.status = status;
		this.createModifiedDate = createModifiedDate;
	}

	public TierMailouts(String appno, String regno, String trackingno, char status, Date createModifiedDate) {
		this.appno = appno;
		this.regno = regno;
		this.trackingno = trackingno;
		this.status = status;
		this.createModifiedDate = createModifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UID", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "appno", nullable = false, length = 45)
	public String getAppno() {
		return this.appno;
	}

	public void setAppno(String appno) {
		this.appno = appno;
	}

	@Column(name = "regno", length = 45)
	public String getRegno() {
		return this.regno;
	}

	public void setRegno(String regno) {
		this.regno = regno;
	}

	@Column(name = "trackingno", nullable = false, length = 45)
	public String getTrackingno() {
		return this.trackingno;
	}

	public void setTrackingno(String trackingno) {
		this.trackingno = trackingno;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Modified_Date", nullable = false, length = 19)
	public Date getCreateModifiedDate() {
		return this.createModifiedDate;
	}

	public void setCreateModifiedDate(Date createModifiedDate) {
		this.createModifiedDate = createModifiedDate;
	}
	
	@Column(name = "company_uid", nullable = false, length = 11)
	public Integer getCompanyuid() {
		return companyuid;
	}

	public void setCompanyuid(Integer companyuid) {
		this.companyuid = companyuid;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Expiration_Date", nullable = false, length = 19)
	public Date getExpirationDate() {
		return expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@Column(name = "RegItem_UID", nullable = false, length = 11)
	public Integer getRegitemuid() {
		return regitemuid;
	}

	public void setRegitemuid(Integer regitemuid) {
		this.regitemuid = regitemuid;
	}

}
